apiVersion: batch/v1
kind: Job
metadata: 
  name: occupy
spec:
  template:
    metadata:
      name: occupy
    spec:
      containers:
      - name: occupy
        image: occupy_v1
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 6
